---
- name: Install apache and upload index.html
  hosts: all
  become: yes

  vars:
    source_link: <center><img src="https://c1.cprnt.com/storage/i/40/4d/3e/2a/2d42434c942c44c3e1f1f0c0/acb66f351e2d588feee7fb0c68f2c0b9.png" alt="Rus - HI! Peace - Da!">
    destin_file: 123

  tasks:
  - name: Install Web Server
    yum: name=apache2 state=latest

  - name: Add Rusni pisda
    ansible.builtin.lineinfile:
      path: /var/www/html/index.html
      line: "{{ source_link }}"
      create: yes
    notify: restart Apache



  handlers:
  - name: restart Apache
    service: name=apache2 state=restarted

