version: "3.9"

services:
  vue-build:
    container_name: vue_build_container
    image: node:12.22.9
    volumes:
      - vue-tutorial:/app
    working_dir: /app
    command: >
      sh -c "git clone https://github.com/taniarascia/vue-tutorial.git && \
             cd vue-tutorial && \
             yarn && \
             yarn build"
    
  vue-serve:
    container_name: vue_serve_container
    image: nginx:latest
    ports:
      - "58158:80"
    volumes:
      - vue-tutorial:/usr/share/nginx/html
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      
volumes:
  vue-tutorial: